// Archivo generado automáticamente por el Pipeline de Gobernanza (Scraper de Maps)
// Fecha de actualización: 2026-04-03 20:50:07
// Total registros: 20

const empresasDatabase = [
    {
        "id": 1,
        "empresa": "Expreso Brio",
        "cuit": "30-50839811-5",
        "provincia": "Santa Fe",
        "ciudad": "S2000 Rosario",
        "direccion": "Av. Acevedo 2949, S2000 Rosario, Santa Fe, Argentina",
        "web": "brio.com.ar",
        "telefono": "+54 810-345-2746",
        "email": "contacto@brio.com.ar",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 49,
        "flotaMax": 74,
        "flotaEstimada": 62,
        "tipoFlota": "Camiones",
        "prioridad": "ALTA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 2,
        "empresa": "Centro 27 - Sucursal Rosario",
        "cuit": "30-53163818-1",
        "provincia": "Santa Fe",
        "ciudad": "S2000 Rosario",
        "direccion": "San Nicolás 3151, S2000 Rosario, Santa Fe, Argentina",
        "web": "centro27.com.ar",
        "telefono": "+54 341 545-5297",
        "email": "contacto@centro27.com.ar",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 81,
        "flotaMax": 122,
        "flotaEstimada": 102,
        "tipoFlota": "Camiones",
        "prioridad": "ALTA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 3,
        "empresa": "Grupo Logístico RedFox",
        "cuit": "30-64871224-0",
        "provincia": "Santa Fe",
        "ciudad": "S2000 Rosario",
        "direccion": "C. 1808 12025, S2000 Rosario, Santa Fe, Argentina",
        "web": "redfox.com.ar",
        "telefono": "+54 9 341 719-2227",
        "email": "contacto@redfox.com.ar",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 32,
        "flotaMax": 48,
        "flotaEstimada": 40,
        "tipoFlota": "Camiones",
        "prioridad": "ALTA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 4,
        "empresa": "FRANSOF S.R.L Logistica Y Distribucion",
        "cuit": "30-70876477-0",
        "provincia": "Santa Fe",
        "ciudad": "S2000 Rosario",
        "direccion": "Uruguay 3356, S2000 Rosario, Santa Fe, Argentina",
        "web": "encomiendasfransof.com",
        "telefono": "+54 9 341 390-7922",
        "email": "contacto@encomiendasfransof.com",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 87,
        "flotaMax": 130,
        "flotaEstimada": 109,
        "tipoFlota": "Camiones",
        "prioridad": "ALTA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 5,
        "empresa": "Logística Cafferata I",
        "cuit": "30-58871276-0",
        "provincia": "Santa Fe",
        "ciudad": "Garay 3642",
        "direccion": "Rosario Santa Fe AR, Garay 3642, S2003 IMF, Argentina",
        "web": "N/A",
        "telefono": "+54 341 559-0171",
        "email": "contacto@empresa.com",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 12,
        "flotaMax": 19,
        "flotaEstimada": 16,
        "tipoFlota": "Camiones",
        "prioridad": "MEDIA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 6,
        "empresa": "Rosario Logistica SA",
        "cuit": "30-68568946-9",
        "provincia": "Santa Fe",
        "ciudad": "S2000 Villa Gdor. Galvez",
        "direccion": "Av. Soldado Alberto Aguirre 3279, S2000 Villa Gdor. Galvez, Santa Fe, Argentina",
        "web": "rosariologistica.com",
        "telefono": "+54 341 317-4646",
        "email": "contacto@rosariologistica.com",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 35,
        "flotaMax": 52,
        "flotaEstimada": 44,
        "tipoFlota": "Camiones",
        "prioridad": "ALTA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 7,
        "empresa": "TDC GRUPO LOGISTICO",
        "cuit": "30-60141195-2",
        "provincia": "Santa Fe",
        "ciudad": "S2000 Rosario",
        "direccion": "Av. Pres. Perón 7759, S2000 Rosario, Santa Fe, Argentina",
        "web": "tdcgrupologistico.com",
        "telefono": "+54 341 459-4087",
        "email": "contacto@tdcgrupologistico.com",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 84,
        "flotaMax": 126,
        "flotaEstimada": 105,
        "tipoFlota": "Camiones",
        "prioridad": "ALTA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 8,
        "empresa": "Urbis Logistica Urbana",
        "cuit": "30-54779855-5",
        "provincia": "Santa Fe",
        "ciudad": "Laprida y",
        "direccion": "Pellegrini, Laprida y, S2000 Rosario, Santa Fe, Argentina",
        "web": "N/A",
        "telefono": "N/A",
        "email": "contacto@empresa.com",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 15,
        "flotaMax": 22,
        "flotaEstimada": 19,
        "tipoFlota": "Camiones",
        "prioridad": "BAJA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 9,
        "empresa": "TLE - Transporte Logístico Entrerriano",
        "cuit": "30-65764062-3",
        "provincia": "Santa Fe",
        "ciudad": "S2013 Rosario",
        "direccion": "Av. Alberdi 25 Bis, S2013 Rosario, Santa Fe, Argentina",
        "web": "tler.com.ar",
        "telefono": "+54 341 612-6111",
        "email": "contacto@tler.com.ar",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 48,
        "flotaMax": 72,
        "flotaEstimada": 60,
        "tipoFlota": "Camiones",
        "prioridad": "ALTA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 10,
        "empresa": "Transporte Tenaglia",
        "cuit": "30-79119270-3",
        "provincia": "Santa Fe",
        "ciudad": "S2013 Rosario",
        "direccion": "Av. Alberdi 25 Bis, S2013 Rosario, Santa Fe, Argentina",
        "web": "tler.com.ar",
        "telefono": "+54 341 612-6111",
        "email": "contacto@tler.com.ar",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 89,
        "flotaMax": 134,
        "flotaEstimada": 112,
        "tipoFlota": "Camiones",
        "prioridad": "ALTA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 11,
        "empresa": "Expreso Demonte",
        "cuit": "30-78186009-9",
        "provincia": "Santa Fe",
        "ciudad": "S2003EHG Rosario",
        "direccion": "San Nicolás 3151, S2003EHG Rosario, Santa Fe, Argentina",
        "web": "expresodemonte.com",
        "telefono": "+54 341 545-5297",
        "email": "contacto@expresodemonte.com",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 84,
        "flotaMax": 127,
        "flotaEstimada": 106,
        "tipoFlota": "Camiones",
        "prioridad": "ALTA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 12,
        "empresa": "Mr Express Rosario",
        "cuit": "30-59892271-8",
        "provincia": "Santa Fe",
        "ciudad": "Sta Fe 3644",
        "direccion": "KUJ Rosario Santa Fe AR, Sta Fe 3644, S2002, Argentina",
        "web": "mrexpresslogistica.com.ar",
        "telefono": "+54 341 679-5244",
        "email": "contacto@mrexpresslogistica.com.ar",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 56,
        "flotaMax": 85,
        "flotaEstimada": 71,
        "tipoFlota": "Camiones",
        "prioridad": "ALTA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 13,
        "empresa": "ESTACIÓN DE CARGAS SAN LORENZO",
        "cuit": "30-71490573-7",
        "provincia": "Santa Fe",
        "ciudad": "S2011 Rosario",
        "direccion": "Av. Ovidio Lagos 5821, S2011 Rosario, Santa Fe, Argentina",
        "web": "N/A",
        "telefono": "+54 341 355-7070",
        "email": "contacto@empresa.com",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 22,
        "flotaMax": 33,
        "flotaEstimada": 28,
        "tipoFlota": "Camiones",
        "prioridad": "MEDIA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 14,
        "empresa": "TRANSPORTE MARGO Y LOGISTICA MG",
        "cuit": "30-62236897-4",
        "provincia": "Santa Fe",
        "ciudad": "S2000 Rosario",
        "direccion": "Blvd. Oroño 4431, S2000 Rosario, Santa Fe, Argentina",
        "web": "N/A",
        "telefono": "+54 2625 63-0026",
        "email": "contacto@empresa.com",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 21,
        "flotaMax": 32,
        "flotaEstimada": 27,
        "tipoFlota": "Camiones",
        "prioridad": "MEDIA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 15,
        "empresa": "Transporte Delfín",
        "cuit": "30-75061724-9",
        "provincia": "Santa Fe",
        "ciudad": "S2004 Rosario",
        "direccion": "Blvd. Oroño 4595, S2004 Rosario, Santa Fe, Argentina",
        "web": "transportedelfin.com",
        "telefono": "+54 341 466-7478",
        "email": "contacto@transportedelfin.com",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 14,
        "flotaMax": 21,
        "flotaEstimada": 18,
        "tipoFlota": "Camiones",
        "prioridad": "ALTA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 16,
        "empresa": "TRANSPORTE SNAIDER SRL - DEPOSITO ROSARIO",
        "cuit": "30-79654406-7",
        "provincia": "Santa Fe",
        "ciudad": "S2004 Rosario",
        "direccion": "Blvd. Oroño 4595, S2004 Rosario, Santa Fe, Argentina",
        "web": "transportedelfin.com",
        "telefono": "+54 341 466-7478",
        "email": "contacto@transportedelfin.com",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 66,
        "flotaMax": 99,
        "flotaEstimada": 83,
        "tipoFlota": "Camiones",
        "prioridad": "ALTA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 17,
        "empresa": "LOGISTICA S.R.L. Futuro",
        "cuit": "30-79836900-5",
        "provincia": "Santa Fe",
        "ciudad": "S2004 Rosario",
        "direccion": "Blvd. Oroño 4595, S2004 Rosario, Santa Fe, Argentina",
        "web": "transportedelfin.com",
        "telefono": "+54 341 466-7478",
        "email": "contacto@transportedelfin.com",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 22,
        "flotaMax": 33,
        "flotaEstimada": 28,
        "tipoFlota": "Camiones",
        "prioridad": "ALTA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 18,
        "empresa": "Logística Corporativa LC",
        "cuit": "30-60136123-4",
        "provincia": "Santa Fe",
        "ciudad": "S2004 Rosario",
        "direccion": "Blvd. Oroño 4595, S2004 Rosario, Santa Fe, Argentina",
        "web": "transportedelfin.com",
        "telefono": "+54 341 466-7478",
        "email": "contacto@transportedelfin.com",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 53,
        "flotaMax": 80,
        "flotaEstimada": 67,
        "tipoFlota": "Camiones",
        "prioridad": "ALTA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 19,
        "empresa": "Transportes \"Conte\" • Cargas Generales",
        "cuit": "30-79993918-6",
        "provincia": "Santa Fe",
        "ciudad": "S2004 Rosario",
        "direccion": "Blvd. Oroño 4595, S2004 Rosario, Santa Fe, Argentina",
        "web": "transportedelfin.com",
        "telefono": "+54 341 466-7478",
        "email": "contacto@transportedelfin.com",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 68,
        "flotaMax": 102,
        "flotaEstimada": 85,
        "tipoFlota": "Camiones",
        "prioridad": "ALTA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    },
    {
        "id": 20,
        "empresa": "Expreso \"El Charrua\" | Sociedad Anonima",
        "cuit": "30-74284827-2",
        "provincia": "Santa Fe",
        "ciudad": "S2004 Rosario",
        "direccion": "Blvd. Oroño 4595, S2004 Rosario, Santa Fe, Argentina",
        "web": "transportedelfin.com",
        "telefono": "+54 341 466-7478",
        "email": "contacto@transportedelfin.com",
        "contacto": "Verificar",
        "cargo": "Directorio",
        "sector": "Empresas,",
        "flotaMin": 13,
        "flotaMax": 20,
        "flotaEstimada": 17,
        "tipoFlota": "Camiones",
        "prioridad": "ALTA",
        "notas": "Prospección automática de Maps. Evaluado por SoAI Worker. Fecha: 2026-04-03.",
        "keywords": [
            "empresas, transporte, logistica",
            "rosario",
            "prospecto"
        ]
    }
];
